services:
  pruebatecsupermercado: # nombre de tu app
    build: pruebatecsupermercado
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d722nn4r85hc73co8frg-a.virginia-postgres.render.com:5432/supermercado_3ilu
      SPRING_DATASOURCE_USERNAME: nancy
      SPRING_DATASOURCE_PASSWORD: 7dTZQxyxuybZsgkjUMbx02vUcauXFisT
    restart: always

# ⚠️ Nota:
# Ya NO necesitas levantar un contenedor de MySQL local,
# porque tu base está en Render (PostgreSQL gestionado).