spring.application.name=pruebaTecSupermercado

spring.datasource.url=jdbc:postgresql://dpg-d722nn4r85hc73co8frg-a/supermercado_3ilu
spring.datasource.username=nancy
spring.datasource.password=7dTZQxyxuybZsgkjUMBx02vUcauXFisT

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/supermercado
server.port=${PORT:8080}
